### ISSUE TITLE
Node red crashes

### ISSUE THREAD

**Issue by embeeweezer** [raweee/node-red-contrib-whatsapp-link#21]
After installing this node, my node-red crashes with the following error:

22 Feb 12:39:59 - [red] Uncaught Exception:
22 Feb 12:39:59 - [error] Error: Failed to launch the browser process! spawn /data/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome ENOENT

TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/data/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at ChildProcess.<anonymous> (/data/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:233:85)
    at ChildProcess.emit (node:events:527:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:289:12)
    at onErrorNT (node:internal/child_process:478:16)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by raweee** [comment]
Please select Whatsapp-Lite in configuration Node. (it will work for you)

![](https://raw.githubusercontent.com/raweee/node-red-contrib-whatsapp-link/master/.github/WhatsaaLite.png)

**Comment by embeeweezer** [comment]
Thank you sir!
