### ISSUE TITLE
Node red crashing

### ISSUE THREAD

**Issue by embeeweezer** [raweee/node-red-contrib-whatsapp-link#22]
Using the 'lite' instead of the 'web' setting, it all worked, until it didn't... I think it happened after I saw the status being 'disconnected' and I injected a payload with 'test' to the WA Admin node. Restarting Node Red did bring the WA Admin status back to 'connected' again.

23 Feb 03:10:17 - [red] Uncaught Exception:
23 Feb 03:10:17 - [error] Error: Connection Closed
    at sendRawMessage (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:50:19)
    at sendNode (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:61:16)
    at Object.sendPresenceUpdate (/data/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:392:19)
    at WhatsappAdmin._inputCallback (/data/node_modules/node-red-contrib-whatsapp-link/admin.js:45:34)

**Comment by embeeweezer** [comment]
Exact same thing happened again:

23 Feb 21:00:20 - [red] Uncaught Exception:
23 Feb 21:00:20 - [error] Error: Connection Closed
    at sendRawMessage (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:50:19)
    at sendNode (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:61:16)
    at Object.sendPresenceUpdate (/data/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:392:19)
    at WhatsappAdmin._inputCallback (/data/node_modules/node-red-contrib-whatsapp-link/admin.js:45:34)
