### ISSUE TITLE
module crash on docker

### ISSUE THREAD

**Issue by zofiel** [raweee/node-red-contrib-whatsapp-link#33]
Hi team,

If I create a whastapp web the node-red container crash directly and i have to borrow iT

If i create the little socker It works fine but after a time crash.

the log:
28 Mar 07:58:51 - [red] Uncaught Exception:
28 Mar 07:58:51 - [error] Error: Connection Closed
    at sendRawMessage (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:50:19)
    at sendNode (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:61:16)
    at Object.sendPresenceUpdate (/data/node_modules/@adiwajshing/baileys/lib/Socket/chats.js:392:19)
    at WhatsappAdmin._inputCallback (/data/node_modules/node-red-contrib-whatsapp-link/admin.js:45:34)

Thanks in advance

**Comment by zofiel** [comment]
The error when I tried to create the whatsapp web connection:

 28 Mar 08:07:36 - [red] Uncaught Exception:
28 Mar 08:07:36 - [error] Error: Failed to launch the browser process! spawn /data/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome ENOENT

**Comment by zofiel** [comment]
another error detected in logs after enable whastapp lite socket:

2023-03-28T06:19:36.902Z 40 undefined | pid=17 hostname=98a6fc27a274 stack=Error: mutex start
    at /data/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:15:31
    at Object.mutex (/data/node_modules/@adiwajshing/baileys/lib/Utils/make-mutex.js:35:15)
    at handleReceipt (/data/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:361:29)
    at execTask (/data/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:554:20)
    at processNodeWithBuffer (/data/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:551:15)
    at WebSocket.<anonymous> (/data/node_modules/@adiwajshing/baileys/lib/Socket/messages-recv.js:566:9)
    at WebSocket.emit (node:events:527:28)
    at /data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:222:35
    at Object.decodeFrame (/data/node_modules/@adiwajshing/baileys/lib/Utils/noise-handler.js:131:17)
    at WebSocket.onMessageRecieved (/data/node_modules/@adiwajshing/baileys/lib/Socket/socket.js:198:15) waitOver=true msg=possible mutex deadlock

**Comment by zofiel** [comment]
Node-red crash, i have to delete the connection info into the flow to restart it again

**Comment by Chimete** [comment]
Me too (the same on Docker)

**Comment by raweee** [comment]
for docker please refer  #10 - [Docker : Nodered crashing: Failed to launch the browser process!](https://github.com/raweee/node-red-contrib-whatsapp-link/issues/10). it might helps.

**Comment by zofiel** [comment]
thanks, it worked
