### ISSUE TITLE
Node-red crashed when i receive a message 

### ISSUE THREAD

**Issue by rubenavas23** [raweee/node-red-contrib-whatsapp-link#46]
Since yesterday node-red is crashing when i receive a message. I tried to delete the connexion and it crashed too. I use the client as a WhatsApp web and this is the message:
9 Jul 11:11:30 - [error] TypeError: Cannot read properties of undefined (reading 'WAClose')
    at WhatsappAdmin._inputCallback (C:\Users\X\.node-red\node_modules\node-red-contrib-whatsapp-link\admin.js:21:33)
    at C:\Users\Rubén Navas\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:210:26
    at Object.trigger (C:\Users\X\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\util\lib\hooks.js:166:13)
    at Node._emitInput (C:\Users\X\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:202:11)
    at Node.emit (C:\Users\X\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:186:25)
    at Node.receive (C:\Users\X\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\nodes\Node.js:485:10)
    at Immediate.<anonymous> (C:\Users\X\AppData\Roaming\npm\node_modules\node-red\node_modules\@node-red\runtime\lib\flows\Flow.js:831:52)
    at process.processImmediate (node:internal/timers:476:21)

**Comment by rubenavas23** [comment]
I realised it crashed when in chat-in, i have some option selected in web event. 
![image](https://github.com/raweee/node-red-contrib-whatsapp-link/assets/61756306/b43af826-add1-428f-8180-3b908939a2b3)
