### ISSUE TITLE
Node-RED Failed to run due to pupeter error: Failed to launch the browser process!

### ISSUE THREAD

**Issue by AKhateeb** [raweee/node-red-contrib-whatsapp-link#54]
I've successfully install `[node-red-contrib-whatsapp-link](https://github.com/raweee/node-red-contrib-whatsapp-link)`

it's working fine using node-red on my local machine, but it failed on server running node-red via Docker

I'm using node-red Docker based on Node-18-alpine, it's well installed but when I'm trying to run Node-Red it failed and shows this error

![image](https://github.com/raweee/node-red-contrib-whatsapp-link/assets/19706280/fe557c46-8d4c-4c1e-a0b1-98198e441a75)

**Comment by shmulyeng** [comment]
I have the same issue. How can I at least remove it so I can start Node-red

**Comment by sp00ktober** [comment]
You need to directly edit the flows.json file and remove the ones from this plugin.
For me this happened when i was using WhatsApp Web. This just crashes my whole node red, very frustraiting..

**Comment by xuaopsd** [comment]
I have the same issue too. Someone found some fix for this one?

**Comment by sp00ktober** [comment]
Yes look one post above yours.

**Comment by xuaopsd** [comment]
> t the flo

Yeah I understand what you mean removing the node causing the problem, also you can run node-red in safe mode and delete the node that are crashing node-red with the UI. I'm asking if there's already a solution to the puppeeter error, we can't use this palette with this error crashing all the node-red.

**Comment by bluepup** [comment]
node-red crashes with:

```
12 Jun 08:24:21 - [info] Starting flows
12 Jun 08:24:21 - [info] [whatsappLink:Web] Status : Initializing Whatsapp..
12 Jun 08:24:21 - [error] [chats-in:8a785cfb4cbebbf7] TypeError: Cannot read properties of null (reading 'client')
12 Jun 08:24:21 - [info] Started flows
12 Jun 08:24:21 - [red] Uncaught Exception:
12 Jun 08:24:21 - [error] Error: Failed to launch the browser process! spawn /data/node_modules/puppeteer-core/.local-chromium/linux-1045629/chrome-linux/chrome ENOENT


TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

    at onClose (/data/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at ChildProcess.<anonymous> (/data/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:293:24)
    at ChildProcess.emit (node:events:517:28)
    at ChildProcess._handle.onexit (node:internal/child_process:290:12)
    at onErrorNT (node:internal/child_process:477:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

please handle the exception and catch the error.

**Comment by S615228530jose** [comment]
Si

**Comment by ivantomic77** [comment]
+1

**Comment by yousefamar** [comment]
If you can, use the socket client ("Lite") instead of the web client. The issue is running chrome inside of a docker container. It's easier to run node-red outside of a Docker container than it is to get chrome to run inside, IMO.

**Comment by bosyying** [comment]
same issue here. So can i say it is so unsafe for us to use node red paleet . because it is all depends on the developer mood. If they feel like to entertain you they support , if they dont want , they can just ignore it. ??

**Comment by yousefamar** [comment]
That's the nature of open source software unfortunately. Unless you're paying the developer, you can't feel entitled to their continued maintenance. You're always free to fork the project and make the fixes yourself. And then have fun getting pestered by people who hold you responsible for free maintenance.

Consider also that WhatsApp is actively hostile to 3rd party integration and have shut down all attempts at APIs, which is why this project has to use libraries that take hacky approaches. If you want to blame someone, blame Meta and capitalism as a whole.
