### ISSUE TITLE
[error] TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by V24885** [raweee/node-red-contrib-whatsapp-link#59]
When scanning the QRcode for the first time it works. However, when reloading, the following error appears:

[error] TypeError: Cannot read properties of null (reading '1')
at LocalWebCache.persist (C:\Users\admin\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
at C:\Users\admin\node_modules\whatsapp-web.js\src\Client.js:744:36
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

this after error, nodered no longer works

**Comment by Sahib1976** [comment]
When scanning the QRcode for the first time it works. However, when reloading, the following error appears:

[error] TypeError: Cannot read properties of null (reading '1')
at LocalWebCache.persist (C:\Users\admin\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
at C:\Users\admin\node_modules\whatsapp-web.js\src\Client.js:744:36
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
I have the same error, when I first load Node-red WhatsApp it connects and then crashes.

help me please.

**Comment by V24885** [comment]
I believe the error is in node-red-contrib-link-whatsapp. If you can resolve it, please report it here.

**Comment by danielfabro** [comment]
I'm also having this same problem. Need help. Does anyone know the solution, please share.
TypeError: Cannot read properties of null (reading '1')
at LocalWebCache.persist (/root/.node-red/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
at /root/.node-red/node_modules/whatsapp-web.js/src/Client.js:744:36

**Comment by sauqi28** [comment]
yes i have same problem, :(

**Comment by rizkihermansyah83** [comment]
i have same ploblems.. help me please sir... thankyou

**Comment by mrameen** [comment]
i have same ploblems.. help me please sir... thankyou

**Comment by mrameen** [comment]
Solved by this Solved by this `https://github.com/raweee/node-red-contrib-whatsapp-link/issues/58`

**Comment by rizkihermansyah83** [comment]
solvet.. mrameen... thankyou very much sir...
