### ISSUE TITLE
[error] TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by rizkihermansyah83** [raweee/node-red-contrib-whatsapp-link#63]
5 Apr 11:33:07 - [error] TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (C:\Users\SALES\.node-red\node_modules\whatsapp-web.js\src\webCache\LocalWebCache.js:34:69)
    at C:\Users\SALES\.node-red\node_modules\whatsapp-web.js\src\Client.js:744:36
    at processTicksAndRejections (node:internal/process/task_queues:95:5)

helpme please sir...thankyou

**Comment by mrameen** [comment]
Solved by this Solved by this `https://github.com/raweee/node-red-contrib-whatsapp-link/issues/58`

**Comment by rizkihermansyah83** [comment]
solvet.. mrameen... thankyou very much sir...
