### ISSUE TITLE
deployed flow nodered container goes in crash

### ISSUE THREAD

**Issue by zaromarco** [raweee/node-red-contrib-whatsapp-link#66]
Hi , i ave installed this into a docker container with node-red v3.1.9 with nodejs v18 but when i deploy the initial flow , nodered goes in crash.
i saw in the log these error:
12 May 09:46:07 - [info] Starting flows
12 May 09:46:07 - [info] [whatsappLink:Web] Status : Initializing Whatsapp..
12 May 09:46:07 - [info] Started flows
12 May 09:46:07 - [red] Uncaught Exception:
12 May 09:46:07 - [error] Error: ENOENT: no such file or directory, mkdir '/.node-red/Whatsapp-Link/session'
    at Object.mkdirSync (node:fs:1391:3)
    at LocalAuth.beforeBrowserInitialized (/data/node_modules/whatsapp-web.js/src/authStrategies/LocalAuth.js:35:12)
    at Client.initialize (/data/node_modules/whatsapp-web.js/src/Client.js:95:33)
    at WAConnect (/data/node_modules/node-red-contrib-whatsapp-link/whatsappLink.js:40:31)
    at new RemoteClientNode (/data/node_modules/node-red-contrib-whatsapp-link/whatsappLink.js:48:22)
    at Object.createNode (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/util.js:190:27)
    at Flow.start (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:235:50)
    at async Object.start [as startFlows] (/usr/src/node-red/node_modules/@node-red/runtime/lib/flows/index.js:403:17)
12 May 09:46:09 - [info] 
Welcome to Node-RED
===================
12 May 09:46:09 - [info] Node-RED version: v3.1.9
12 May 09:46:09 - [info] Node.js  version: v18.20.2
12 May 09:46:09 - [info] Linux 4.4.302+ x64 LE

where do i need to make this directory?

**Comment by zaromarco** [comment]
Any news?
