### ISSUE TITLE
TypeError: Cannot read properties of null (reading '1')

### ISSUE THREAD

**Issue by billyrudi** [raweee/node-red-contrib-whatsapp-link#72]
i have already olved thys i may but now i'm not able to solve it ! Help me!
i have changed Constants.js  to 
 webVersion: '2.2410.1',
    webVersionCache: {
        type: 'remote',
        remotePath: 'https://raw.githubusercontent.com/wppconnect-team/wa-version/main/html/2.2410.1.html',
    },
but nothing

[red] Uncaught Exception:
24 Jun 14:19:31 - [error] TypeError: Cannot read properties of null (reading '1')
    at LocalWebCache.persist (/home/debian/.node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/whatsapp-web.js/src/webCache/LocalWebCache.js:34:69)
    at /home/debian/.node-red/node_modules/node-red-contrib-whatsapp-link/node_modules/whatsapp-web.js/src/Client.js:786:36
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by V24885** [comment]
Has anyone managed to solve it?
