### ISSUE TITLE
WA Admin (web), crash fresh install NodeRed

### ISSUE THREAD

**Issue by bosyying** [raweee/node-red-contrib-whatsapp-link#77]
Cannot register on Lite type. 

then i change to Web type. Then it crash the whole node red. 

`24 Aug 08:40:37 - [info] [whatsappLink:Web] Status : Initializing Whatsapp..
24 Aug 08:40:37 - [info] Started flows
24 Aug 08:40:37 - [red] Uncaught Exception:
24 Aug 08:40:37 - [error] Error: Failed to launch the browser process! spawn /data/node_modules/puppeteer-core/.local-chromium/linux-1045629/chrome-linux/chrome ENOENT
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/data/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at ChildProcess.<anonymous> (/data/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:293:24)
    at ChildProcess.emit (node:events:519:28)
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)`

![image](https://github.com/user-attachments/assets/2408deda-2404-4f7b-a148-0aaa0bf18817)

**Comment by laflaf3d** [comment]
Hi, 
after installing the node and configure it, my node-red fall into perptual crash:

```
/home/pi/.node-red/node_modules/puppeteer-core/.local-chromium/linux-1045629/chrome-linux/chrome: 1: Syntax error: Unterminated quoted string
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/home/pi/.node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
    at Interface.<anonymous> (/home/pi/.node-red/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:287:24)
    at Interface.emit (node:events:531:35)
    at Interface.close (node:internal/readline/interface:528:10)
    at Socket.onend (node:internal/readline/interface:254:10)
    at Socket.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
nodered.service: Main process exited, code=exited, status=1/FAILURE
nodered.service: Failed with result 'exit-code'.
nodered.service: Consumed 21.971s CPU time.
xterm-256colornodered.service: Scheduled restart job, restart counter is at 31.
Stopped nodered.service - Node-RED graphical event wiring tool.
nodered.service: Consumed 21.971s CPU time.
Started nodered.service - Node-RED graphical event wiring tool.
2 Oct 17:33:46 - [info]
Welcome to Node-RED
===================
2 Oct 17:33:46 - [info] Node-RED version: v4.0.3
2 Oct 17:33:46 - [info] Node.js  version: v20.17.0
2 Oct 17:33:46 - [info] Linux 6.6.31+rpt-rpi-v7 arm LE
2 Oct 17:33:48 - [info] Loading palette nodes
2 Oct 17:33:53 - [info] Dashboard version 3.6.5 started at /ui
2 Oct 17:33:56 - [info] Settings file  : /home/pi/.node-red/settings.js
2 Oct 17:33:56 - [info] Context store  : 'default' [module=memory]
2 Oct 17:33:56 - [info] User directory : /home/pi/.node-red
2 Oct 17:33:56 - [warn] Projects disabled : editorTheme.projects.enabled=false
2 Oct 17:33:56 - [info] Flows file     : /home/pi/.node-red/flows.json
2 Oct 17:33:56 - [info] Server now running at http://127.0.0.1:1880/
2 Oct 17:33:56 - [info] Starting flows
```

**Comment by sm4l** [comment]
i got the same error

**Comment by MrAredhone** [comment]
is there already a solution for this since im haveing the same problem

**Comment by laflaf3d** [comment]
Merci ! 

Yahoo Mail : Recherchez, organisez, maîtrisez 
 
  Le lun., janv. 27, 2025 à 15:21, ***@***.***> a écrit:   


is there already a solution for this since im haveing the same problem

**Comment by cotwild** [comment]
same here... any news?

**Comment by LucasBorges4** [comment]
hello guys the solution consistis in change the local executable path downloadin a new google chrome binaries

![Image](https://github.com/user-attachments/assets/d2a26823-07c5-4d7c-8f23-02bd79471c5c)

@cotwild  @laflaf3d @sm4l @bosyying @MrAredhone 

Im using idx.google, but it can be applied in Docker.

**Comment by quintonschemel** [comment]
WA pics up that their service is being used and somehow manages to do something that causes the server to crash all the time. My mobile number was blocked even though I was not spamming. If I use a different mobile number and sometimes fresh install of nodered it can work for a few weeks to months and then crashes all the time again. Telegram is still #1 messaging service for Node-Red.

**Comment by fgdur789-cyber** [comment]
After setup WA admin node  Node-red crash 

<img width="1054" height="618" alt="Image" src="https://github.com/user-attachments/assets/d580340d-6770-43df-bd42-1ebba6fceaaf" />

please give some suggestion on what to do about it . It looks there is some problem with puppetree. After clearing flow.json i can start node-red again

**Comment by quintonschemel** [comment]
I stopped using WA because I couldn't get it stable and now use telegram instead. Much more stable and more useful nodes. Please share if you are able to get it fixed and stable for a long time. Some of my customers prefer WA and would like to still be able to use it.

The only other way for me was to use WhatsApp Whin node and do http request instead and pay for the api.

**Comment by Michal8519** [comment]
in file ...node-red-contrib-whatsapp-link/whatsappLink.js I add  "browser : 'firefox'," or "browser : 'chromium'," and Node-RED doesn't crash but I still have an error in the console:

![Image](https://github.com/user-attachments/assets/f6fa0d56-e8e9-4c49-b222-31840be8f498)

**Comment by Michal8519** [comment]
The solution for me was to use Firefox instead of Chrome.
First, I added the following line to the file
.../node-red-contrib-whatsapp-link/whatsappLink.js:
browser: 'firefox',

<img width="507" height="422" alt="Image" src="https://github.com/user-attachments/assets/caa50113-71a5-494c-b0fa-6c50646b7d1c" />

Next, I ran this command in the terminal:
npx puppeteer browsers install firefox

And after that, WA Admin works correctly with waWebClient on the Raspberry Pi.

When I encounter an error like the one below:

<img width="1080" height="165" alt="Image" src="https://github.com/user-attachments/assets/e3cf7809-ec90-4cc2-bf50-91c6ed8119bc" />

I remove the /home/pi/.node-red/Whatsapp-Link/session/ folder
