### ISSUE TITLE
Unable to send whatsapp group message

### ISSUE THREAD

**Issue by ABMAuto** [raweee/node-red-contrib-whatsapp-link#82]
Hello everyone. Sorry if I'm going to make some mistakes or say something nonsensical, but I'm new and I'm using node-red for the first time. 
I need to send messages through whatsapp without third-party API, so I'm trying to use node-red-contrib-whatsapp-link. I did some tests and I saw how to send a message to a specific number, also using the user id. For the time being, all tests have been performed using a fixed string as a message.
My goal, unfortunately, is to send a message to a group. I then used the group-out node, but without any success. I also use the node to send the message to a specific user id, but when I enter a group id I always get the following error:

Error Sending Msg: Error: Evaluation failed: Error: wid error: invalid wid
    at new Error (<anonymous>:6:31)
    at h (https://static.whatsapp.net/rsrc.php/v4/yE/r/TWv--ur-f8P.js:71:191)
    at new a (https://static.whatsapp.net/rsrc.php/v4/yN/r/7ElHmQwwC83.js:100:1558)
    at Object.o [as createWid] (https://static.whatsapp.net/rsrc.php/v4/yN/r/7ElHmQwwC83.js:102:909)
    at pptr://__puppeteer_evaluation_script__:2:49

I used a Group ID in the form: "group_id"@g.us
node version: v22.12.0
npm  version: 11.0.0
node-red-contrib-whatsapp-link: 0.1.39-C

Can anyone help me? 
Thank a lot

**Comment by JaMateoslu** [comment]
Same error here, I have tried all the possible approaches. 

I am able to read all and send messages to indidivual contacts but not able to send messages through groups. 

Has anyone been able to send these?

I have tried with msg.chatID and the remote one like the one shared  "group_id"@g.us but no success

"Error Sending Msg:: Error: item-not-found"

**Comment by pbenav** [comment]
Nope!. I have the same problem. I can't send messages to older groups with ID in the format mobilenumber-chat@g,us and can't find a way to solve it.

Anyway I can see that there is not too much movement in this issues page since a long time.
Is this project active?

Thanks a lot for your answers!.

**Comment by pbenav** [comment]
Found it!
There is  a couple of mistyping in code. 

Check socNubmerSeteing. It should be socNumberSetting

And so a couple more. I'm going to submit a pull request.
