### ISSUE TITLE
Not able to connect

### ISSUE THREAD

**Issue by deblasioluca** [raweee/node-red-contrib-whatsapp-link#9]
I've just installed the whatsapp-link 0.1.29 and am not able to connect. I've deleted the session folder which did not lead to an improvement. Also the mentioned line in node_modules\whatsapp-web.js\src\util\Injected.js is not available to comment out.

**Comment by raweee** [comment]
Can show the error ( shown in terminal)

**Comment by deblasioluca** [comment]
I don't get an error. The WA Admin node stays on "Connecting whatsapp..." and will not connect.

**Comment by raweee** [comment]
Thats a first time... 
Actually, I need to know the error if any.. (it might not able to connect the whatsapp.)

**Comment by deblasioluca** [comment]
Hi Ravi
If you could guide me how to see error message, that would be great. 
I've newly added the WhatsApp-link node to my node red yesterday with the latest version. As per guideline, then added the admin node to my flow and deployed it after "defining" the WhatsApp link. After deployment, admin link shows "connecting WhatsApp" and remains in this status. No other message is show.

**Comment by talkleasy** [comment]
I have the same issue. I get the 'Connecting' text in the flow, but the QR code never appears. Have tried multiple times. Could this be region based as I am in the UK? How do I check the NR error log? Thanks.

**Comment by deblasioluca** [comment]
Hi Ravi

Please find below the journalctl output for nodred. This is the situation when i inject a restart into the WA Admin node:

18 Jan 21:07:08 - [info] [whatsappLink:Web] Status : Initializing Whatsapp..
(node:14839) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
    at Client.destroy (/home/<user>/.node-red/node_modules/whatsapp-web.js/src/Client.js:569:31)
    at WAClose (/home/<user>/.node-red/node_modules/node-red-contrib-whatsapp-link/whatsappLink.js:76:24)
    at WhatsappAdmin.WARestart (/home/<user>/.node-red/node_modules/node-red-contrib-whatsapp-link/whatsappLink.js:101:13)
    at WhatsappAdmin._inputCallback (/home/<user>/.node-red/node_modules/node-red-contrib-whatsapp-link/admin.js:34:22)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at WhatsappAdmin.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at WhatsappAdmin.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at WhatsappAdmin.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10)
    at Immediate.<anonymous> (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (internal/timers.js:464:21)
(node:14839) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 10)
(node:14839) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'close' of null
    at Client.destroy (/home/<user>/.node-red/node_modules/whatsapp-web.js/src/Client.js:569:31)
    at WAClose (/home/<user>/.node-red/node_modules/node-red-contrib-whatsapp-link/whatsappLink.js:77:31)
    at WhatsappAdmin.WARestart (/home/<user>/.node-red/node_modules/node-red-contrib-whatsapp-link/whatsappLink.js:101:13)
    at WhatsappAdmin._inputCallback (/home/<user>/.node-red/node_modules/node-red-contrib-whatsapp-link/admin.js:34:22)
    at /usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:210:26
    at Object.trigger (/usr/lib/node_modules/node-red/node_modules/@node-red/util/lib/hooks.js:166:13)
    at WhatsappAdmin.Node._emitInput (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:202:11)
    at WhatsappAdmin.Node.emit (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:186:25)
    at WhatsappAdmin.Node.receive (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/nodes/Node.js:485:10)
    at Immediate.<anonymous> (/usr/lib/node_modules/node-red/node_modules/@node-red/runtime/lib/flows/Flow.js:831:52)
    at processImmediate (internal/timers.js:464:21)
(node:14839) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 11)
(node:14839) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/home/<user>/.node-red/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: 16: Syntax error: ")" unexpected
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
    at onClose (/home/<user>/.node-red/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:241:20)
    at Interface.<anonymous> (/home/<user>/.node-red/node_modules/puppeteer/lib/cjs/puppeteer/node/BrowserRunner.js:231:68)
    at Interface.emit (events.js:412:35)
    at Interface.close (readline.js:530:8)
    at Socket.onend (readline.js:254:10)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1333:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(node:14839) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 12)
18 Jan 21:07:12 - [info] [whatsappLink:Web] Error : Waiting for Initializion...
18 Jan 21:07:22 - [info] [whatsappLink:Web] Error : Waiting for Initializion...

**Comment by raweee** [comment]
Hi, 
WhatsApp-link require chrome in background to emulate offical whatsapp web instance. Node use Puppeteer to automate these processes. 
But in your case node is not able to start chrome in background so it remains connecting. 

And when you restart there was nothing to close in first place. So the Error

**Comment by raweee** [comment]
I know WhatsappLink node req. lots of dependencies to run chrome and Puppeteer in background (because it have to emulate whatsapp web).
To solve this I'm already working on a light version "whatsappLite" which use only web sockets in background. It will small in size and eat less RAM( no chrome/ Puppeteer).
Hope that node 'whatsappLite' will be completed this Sunday.

**Comment by talkleasy** [comment]
Thanks Raweee - looking forward to the lite version as I canot get it to work as is:
(node:270) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process!
/root/.node-red/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: 16: /root/.node-red/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: Syntax error: ")" unexpected
TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

**Comment by deblasioluca** [comment]
> Thanks Raweee - looking forward to the lite version as I canot get it to work as is: (node:270) UnhandledPromiseRejectionWarning: Error: Failed to launch the browser process! /root/.node-red/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: 16: /root/.node-red/node_modules/puppeteer/.local-chromium/linux-982053/chrome-linux/chrome: Syntax error: ")" unexpected TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md

https://chsamii.medium.com/puppeteer-on-raspbian-nodejs-3425ccea470e

**Comment by talkleasy** [comment]
Looking forward to the Lite version Raweee.

**Comment by raweee** [comment]
> Looking forward to the Lite version Raweee.

WhatsApp lite will be available tomorrow in beta mode for testing.

**Comment by raweee** [comment]
Please test the lite sockets version. It might work for you

**Comment by talkleasy** [comment]
Hi

Thanks for this. However, installation failed with the following error messages:
2023-01-26T08:44:15.174Z Install : node-red-contrib-whatsapp-link 0.1.32

2023-01-26T08:44:09.015Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-whatsapp-link@0.1.32
2023-01-26T08:45:41.661Z [err] npm
2023-01-26T08:45:41.673Z [err]  ERR! code ENOENT
2023-01-26T08:45:41.673Z [err] npm ERR! syscall spawn git
2023-01-26T08:45:41.673Z [err] npm ERR! path git
2023-01-26T08:45:41.686Z [err] npm
2023-01-26T08:45:41.688Z [err]  
2023-01-26T08:45:41.693Z [err] ERR! errno -2
2023-01-26T08:45:41.799Z [err] npm
2023-01-26T08:45:41.801Z [err]  
2023-01-26T08:45:41.813Z [err] ERR! enoent Error while executing:
2023-01-26T08:45:41.813Z [err] npm ERR! enoent undefined ls-remote -h -t https://github.com/adiwajshing/libsignal-node.git
2023-01-26T08:45:41.813Z [err] npm ERR! enoent 
2023-01-26T08:45:41.813Z [err] npm ERR! enoent 
2023-01-26T08:45:41.813Z [err] npm ERR! enoent spawn git ENOENT
2023-01-26T08:45:41.813Z [err] npm ERR! enoent This is related to npm not being able to find a file.
2023-01-26T08:45:41.813Z [err] npm 
2023-01-26T08:45:41.815Z [err] ERR!
2023-01-26T08:45:41.816Z [err]  
2023-01-26T08:45:41.818Z [err] enoent
2023-01-26T08:45:41.822Z [err]  
2023-01-26T08:45:41.928Z [err] 
2023-01-26T08:45:41.971Z [err] npm ERR! A complete log of this run can be found in:
2023-01-26T08:45:41.971Z [err] npm ERR!     /root/.npm/_logs/2023-01-26T08_45_41_886Z-debug.log
2023-01-26T08:45:42.015Z rc=254

Look forward to a revision.

**Comment by talkleasy** [comment]
Still have an install error on the revised version:

-----------------------------------------------------------
2023-01-26T14:40:58.897Z Install : node-red-contrib-whatsapp-link 0.1.32-A

2023-01-26T14:40:52.568Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-whatsapp-link@0.1.32-A
2023-01-26T14:41:59.484Z [err] npm
2023-01-26T14:41:59.487Z [err]  
2023-01-26T14:41:59.489Z [err] ERR!
2023-01-26T14:41:59.490Z [err]  
2023-01-26T14:41:59.503Z [err] code ENOENT
2023-01-26T14:41:59.503Z [err] npm ERR! syscall spawn git
2023-01-26T14:41:59.503Z [err] npm ERR! path git
2023-01-26T14:41:59.504Z [err] npm
2023-01-26T14:41:59.506Z [err]  
2023-01-26T14:41:59.507Z [err] ERR!
2023-01-26T14:41:59.509Z [err]  
2023-01-26T14:41:59.522Z [err] errno -2
2023-01-26T14:41:59.616Z [err] npm
2023-01-26T14:41:59.617Z [err]  
2023-01-26T14:41:59.619Z [err] ERR!
2023-01-26T14:41:59.633Z [err]  enoent Error while executing:
2023-01-26T14:41:59.633Z [err] npm ERR! enoent undefined ls-remote -h -t https://github.com/adiwajshing/libsignal-node.git
2023-01-26T14:41:59.633Z [err] npm ERR! enoent 
2023-01-26T14:41:59.633Z [err] npm ERR! enoent 
2023-01-26T14:41:59.633Z [err] npm ERR! enoent spawn git ENOENT
2023-01-26T14:41:59.633Z [err] npm ERR! enoent This is related to npm not being able to find a file.
2023-01-26T14:41:59.633Z [err] npm ERR! enoent 
2023-01-26T14:41:59.696Z [err] 
2023-01-26T14:41:59.698Z [err] npm
2023-01-26T14:41:59.700Z [err]  
2023-01-26T14:41:59.701Z [err] ERR!
2023-01-26T14:41:59.709Z [err]  A complete log of this run can be found in:
2023-01-26T14:41:59.709Z [err] npm ERR!     /root/.npm/_logs/2023-01-26T14_41_59_658Z-debug.log
2023-01-26T14:41:59.760Z rc=254

**Comment by talkleasy** [comment]
Unfortunately still will not install. Any suggestions please?

-----------------------------------------------------------
2023-02-13T15:06:31.225Z Install : node-red-contrib-whatsapp-link 0.1.34

2023-02-13T15:06:31.185Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-whatsapp-link@0.1.34
2023-02-13T15:07:52.618Z [err] npm
2023-02-13T15:07:52.620Z [err]  
2023-02-13T15:07:52.622Z [err] ERR!
2023-02-13T15:07:52.624Z [err]  
2023-02-13T15:07:52.637Z [err] code ENOENT
2023-02-13T15:07:52.637Z [err] npm ERR! syscall spawn git
2023-02-13T15:07:52.637Z [err] npm ERR! path git
2023-02-13T15:07:52.647Z [err] npm
2023-02-13T15:07:52.649Z [err]  
2023-02-13T15:07:52.650Z [err] ERR!
2023-02-13T15:07:52.657Z [err]  errno -2
2023-02-13T15:07:52.758Z [err] npm
2023-02-13T15:07:52.759Z [err]  
2023-02-13T15:07:52.761Z [err] ERR!
2023-02-13T15:07:52.767Z [err]  enoent Error while executing:
2023-02-13T15:07:52.767Z [err] npm ERR! enoent undefined ls-remote -h -t https://github.com/adiwajshing/libsignal-node.git
2023-02-13T15:07:52.767Z [err] npm ERR! enoent 
2023-02-13T15:07:52.767Z [err] npm
2023-02-13T15:07:52.769Z [err]  
2023-02-13T15:07:52.771Z [err] ERR!
2023-02-13T15:07:52.772Z [err]  
2023-02-13T15:07:52.774Z [err] enoent
2023-02-13T15:07:52.777Z [err]  
2023-02-13T15:07:52.777Z [err] npm ERR!
2023-02-13T15:07:52.787Z [err]  enoent spawn git ENOENT
2023-02-13T15:07:52.787Z [err] npm ERR! enoent This is related to npm not being able to find a file.
2023-02-13T15:07:52.787Z [err] npm ERR! enoent 
2023-02-13T15:07:52.884Z [err] 
2023-02-13T15:07:52.887Z [err] npm
2023-02-13T15:07:52.888Z [err]  
2023-02-13T15:07:52.890Z [err] ERR!
2023-02-13T15:07:52.897Z [err]  A complete log of this run can be found in:
2023-02-13T15:07:52.897Z [err] npm ERR!     /root/.npm/_logs/2023-02-13T15_07_52_840Z-debug.log
2023-02-13T15:07:52.954Z rc=254

**Comment by talkleasy** [comment]
Still won't install :( Any ideas?

-----------------------------------------------------------
2023-02-14T13:34:31.779Z Install : node-red-contrib-whatsapp-link 0.1.34-A

2023-02-14T13:34:31.810Z npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-contrib-whatsapp-link@0.1.34-A
2023-02-14T13:35:53.037Z [err] npm
2023-02-14T13:35:53.040Z [err]  
2023-02-14T13:35:53.042Z [err] ERR!
2023-02-14T13:35:53.044Z [err]  
2023-02-14T13:35:53.045Z [err] code
2023-02-14T13:35:53.057Z [err]  ENOENT
2023-02-14T13:35:53.057Z [err] npm ERR! syscall spawn git
2023-02-14T13:35:53.057Z [err] npm ERR! path git
2023-02-14T13:35:53.068Z [err] npm
2023-02-14T13:35:53.069Z [err]  
2023-02-14T13:35:53.071Z [err] ERR!
2023-02-14T13:35:53.077Z [err]  errno -2
2023-02-14T13:35:53.177Z [err] npm
2023-02-14T13:35:53.179Z [err]  
2023-02-14T13:35:53.181Z [err] ERR!
2023-02-14T13:35:53.187Z [err]  enoent Error while executing:
2023-02-14T13:35:53.187Z [err] npm ERR! enoent undefined ls-remote -h -t https://github.com/adiwajshing/libsignal-node.git
2023-02-14T13:35:53.187Z [err] npm ERR! enoent 
2023-02-14T13:35:53.187Z [err] npm ERR!
2023-02-14T13:35:53.189Z [err]  
2023-02-14T13:35:53.191Z [err] enoent
2023-02-14T13:35:53.192Z [err]  
2023-02-14T13:35:53.197Z [err] npm ERR! enoent spawn git ENOENT
2023-02-14T13:35:53.197Z [err] npm ERR! enoent This is related to npm not being able to find a file.
2023-02-14T13:35:53.199Z [err] npm
2023-02-14T13:35:53.201Z [err]  
2023-02-14T13:35:53.202Z [err] ERR!
2023-02-14T13:35:53.207Z [err]  enoent 
2023-02-14T13:35:53.299Z [err] 
2023-02-14T13:35:53.302Z [err] npm
2023-02-14T13:35:53.303Z [err]  
2023-02-14T13:35:53.305Z [err] ERR!
2023-02-14T13:35:53.313Z [err]  A complete log of this run can be found in:
2023-02-14T13:35:53.313Z [err] npm ERR!     /root/.npm/_logs/2023-02-14T13_35_53_262Z-debug.log
2023-02-14T13:35:53.367Z rc=254

**Comment by raweee** [comment]
Hi @talkleasy, 
these are npm errors or some node_module related errors, try to search online, you might get solution.

**Comment by talkleasy** [comment]
Here's the full log:
npm ERR! code ENOENT
npm ERR! syscall spawn git
npm ERR! path git
npm ERR! errno -2
npm ERR! enoent Error while executing:
npm ERR! enoent undefined ls-remote -h -t https://github.com/adiwajshing/libsignal-node.git
npm ERR! enoent 
npm ERR! enoent 
npm ERR! enoent spawn git ENOENT
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2023-02-16T09_31_05_944Z-debug.log
root@NewStudyPi:~# cat /root/.npm/_logs/2023-02-16T09_31_05_944Z-debug.log
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   'i',
1 verbose cli   'node-red-contrib-whatsapp-link'
1 verbose cli ]
2 info using npm@6.14.13
3 info using node@v14.17.0
4 verbose config Skipping project config: /root/.npmrc. (matches userconfig)
5 verbose npm-session b8113b711dde3cb2
6 silly install loadCurrentTree
7 silly install readLocalPackageData
8 http fetch GET 304 https://registry.npmjs.org/node-red-contrib-whatsapp-link 2736ms (from cache)
9 http fetch GET 200 https://registry.npmjs.org/node-red-contrib-whatsapp-link/-/node-red-contrib-whatsapp-link-0.1.34-A.tgz 498ms (from cache)
10 silly pacote tag manifest for node-red-contrib-whatsapp-link@latest fetched in 3642ms
11 timing stage:loadCurrentTree Completed in 9435ms
12 silly install loadIdealTree
13 silly install cloneCurrentTreeToIdealTree
14 timing stage:loadIdealTree:cloneCurrentTree Completed in 34ms
15 silly install loadShrinkwrap
16 timing stage:loadIdealTree:loadShrinkwrap Completed in 2400ms
17 silly install loadAllDepsIntoIdealTree
18 silly resolveWithNewModule node-red-contrib-whatsapp-link@0.1.34-A checking installable status
19 http fetch GET 304 https://registry.npmjs.org/pino 1559ms (from cache)
20 silly pacote tag manifest for pino@latest fetched in 1786ms
21 silly resolveWithNewModule pino@8.10.0 checking installable status
22 http fetch GET 304 https://registry.npmjs.org/whatsapp-web.js 2442ms (from cache)
23 silly pacote tag manifest for whatsapp-web.js@latest fetched in 2547ms
24 silly resolveWithNewModule whatsapp-web.js@1.19.4 checking installable status
25 http fetch GET 304 https://registry.npmjs.org/qrcode 2497ms (from cache)
26 silly pacote range manifest for qrcode@^1.5.1 fetched in 2638ms
27 silly resolveWithNewModule qrcode@1.5.1 checking installable status
28 http fetch GET 304 https://registry.npmjs.org/@adiwajshing%2fbaileys 3204ms (from cache)
29 silly pacote tag manifest for @adiwajshing/baileys@latest fetched in 3304ms
30 silly resolveWithNewModule @adiwajshing/baileys@5.0.0 checking installable status
31 silly pacote range manifest for pino@^7.0.0 fetched in 595ms
32 silly resolveWithNewModule pino@7.11.0 checking installable status
33 silly fetchPackageMetaData error for libsignal@git+https://github.com/adiwajshing/libsignal-node.git Error while executing:
33 silly fetchPackageMetaData undefined ls-remote -h -t https://github.com/adiwajshing/libsignal-node.git
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData
33 silly fetchPackageMetaData spawn git ENOENT
34 http fetch GET 304 https://registry.npmjs.org/node-cache 2753ms (from cache)
35 silly pacote range manifest for node-cache@^5.1.2 fetched in 2931ms
36 silly resolveWithNewModule node-cache@5.1.2 checking installable status
37 http fetch GET 304 https://registry.npmjs.org/axios 3308ms (from cache)
38 http fetch GET 304 https://registry.npmjs.org/ws 3048ms (from cache)
39 http fetch GET 304 https://registry.npmjs.org/protobufjs 3130ms (from cache)
40 http fetch GET 304 https://registry.npmjs.org/futoin-hkdf 4256ms (from cache)
41 silly pacote range manifest for axios@^0.24.0 fetched in 4582ms
42 silly resolveWithNewModule axios@0.24.0 checking installable status
43 silly pacote range manifest for protobufjs@^6.11.3 fetched in 4307ms
44 silly resolveWithNewModule protobufjs@6.11.3 checking installable status
45 silly pacote range manifest for futoin-hkdf@^1.5.1 fetched in 5145ms
46 silly resolveWithNewModule futoin-hkdf@1.5.1 checking installable status
47 http fetch GET 304 https://registry.npmjs.org/@hapi%2fboom 5205ms (from cache)
48 http fetch GET 304 https://registry.npmjs.org/music-metadata 4996ms (from cache)
49 silly pacote range manifest for @hapi/boom@^9.1.3 fetched in 5529ms
50 silly resolveWithNewModule @hapi/boom@9.1.4 checking installable status
51 silly pacote range manifest for music-metadata@^7.12.3 fetched in 5262ms
52 silly resolveWithNewModule music-metadata@7.13.3 checking installable status
53 http fetch GET 200 https://registry.npmjs.org/ws/-/ws-8.12.1.tgz 1659ms
54 silly pacote range manifest for ws@^8.0.0 fetched in 5355ms
55 silly resolveWithNewModule ws@8.12.1 checking installable status
56 timing stage:rollbackFailedOptional Completed in 27ms
57 timing stage:runTopLevelLifecycles Completed in 21357ms
58 silly saveTree root
58 silly saveTree ├─┬ asn1@0.2.6
58 silly saveTree │ └── safer-buffer@2.1.2
58 silly saveTree ├─┬ async@2.6.2
58 silly saveTree │ └── lodash@4.17.19
58 silly saveTree ├─┬ bcrypt-pbkdf@1.0.2
58 silly saveTree │ └── tweetnacl@0.14.5
58 silly saveTree ├── buildcheck@0.0.3
58 silly saveTree ├── byline@5.0.0
58 silly saveTree ├─┬ caller-id@0.1.0
58 silly saveTree │ └── stack-trace@0.0.10
58 silly saveTree ├── co@3.1.0
58 silly saveTree ├─┬ cpu-features@0.0.4
58 silly saveTree │ └── nan@2.16.0
58 silly saveTree ├─┬ debug@3.1.0
58 silly saveTree │ └── ms@2.0.0
58 silly saveTree ├─┬ domain@0.0.1
58 silly saveTree │ ├─┬ eventstore@1.15.5
58 silly saveTree │ │ ├── dotty@0.0.2
58 silly saveTree │ │ ├── jsondate@0.0.1
58 silly saveTree │ │ ├── parent-require@1.0.0
58 silly saveTree │ │ ├─┬ tolerance@1.0.0
58 silly saveTree │ │ │ └── retry@0.13.1
58 silly saveTree │ │ └── uuid@3.3.3
58 silly saveTree │ ├─┬ shortid@2.2.16
58 silly saveTree │ │ └── nanoid@2.1.11
58 silly saveTree │ ├─┬ should@4.6.5
58 silly saveTree │ │ ├─┬ should-equal@0.3.1
58 silly saveTree │ │ │ └── should-type@0.0.4
58 silly saveTree │ │ ├── should-format@0.0.7
58 silly saveTree │ │ └── should-type@0.0.4
58 silly saveTree │ └── thunkify@2.1.2
58 silly saveTree ├── dotty@0.0.2
58 silly saveTree ├── emitter-component@1.1.1
58 silly saveTree ├── eventstore@1.15.5
58 silly saveTree ├── filesize@3.6.1
58 silly saveTree ├── fs@0.0.2
58 silly saveTree ├── jsondate@0.0.1
58 silly saveTree ├── lodash@4.17.19
58 silly saveTree ├── moment@2.29.4
58 silly saveTree ├── ms@2.0.0
58 silly saveTree ├── nan@2.16.0
58 silly saveTree ├── nanoid@2.1.11
58 silly saveTree ├─┬ node-red-biglib@1.3.4
58 silly saveTree │ ├── byline@4.2.2
58 silly saveTree │ ├── shell-quote@1.7.3
58 silly saveTree │ └── stream@0.0.2
58 silly saveTree ├─┬ node-red-contrib-whatsapp-link@0.1.34-A
58 silly saveTree │ ├─┬ @adiwajshing/baileys@5.0.0
58 silly saveTree │ │ ├── @hapi/boom@9.1.4
58 silly saveTree │ │ ├── axios@0.24.0
58 silly saveTree │ │ ├── futoin-hkdf@1.5.1
58 silly saveTree │ │ ├── music-metadata@7.13.3
58 silly saveTree │ │ ├── node-cache@5.1.2
58 silly saveTree │ │ ├── pino@7.11.0
58 silly saveTree │ │ ├── protobufjs@6.11.3
58 silly saveTree │ │ └── ws@8.12.1
58 silly saveTree │ ├── pino@8.10.0
58 silly saveTree │ ├── qrcode@1.5.1
58 silly saveTree │ └── whatsapp-web.js@1.19.4
58 silly saveTree ├── parent-require@1.0.0
58 silly saveTree ├── retry@0.13.1
58 silly saveTree ├── safer-buffer@2.1.2
58 silly saveTree ├── shell-quote@1.7.3
58 silly saveTree ├── shortid@2.2.16
58 silly saveTree ├── should-equal@0.3.1
58 silly saveTree ├── should-format@0.0.7
58 silly saveTree ├── should-type@0.0.4
58 silly saveTree ├── should@4.6.5
58 silly saveTree ├── ssh2@1.11.0
58 silly saveTree ├── stack-trace@0.0.10
58 silly saveTree ├── stream@0.0.2
58 silly saveTree ├── thunkify@2.1.2
58 silly saveTree ├── tolerance@1.0.0
58 silly saveTree ├── tweetnacl@0.14.5
58 silly saveTree └── uuid@3.3.3
59 verbose stack Error: spawn git ENOENT
59 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
59 verbose stack     at onErrorNT (internal/child_process.js:467:16)
59 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:82:21)
60 verbose cwd /root
61 verbose Linux 5.4.83+
62 verbose argv "/usr/bin/node" "/usr/bin/npm" "i" "node-red-contrib-whatsapp-link"
63 verbose node v14.17.0
64 verbose npm  v6.14.13
65 error code ENOENT
66 error syscall spawn git
67 error path git
68 error errno -2
69 error enoent Error while executing:
69 error enoent undefined ls-remote -h -t https://github.com/adiwajshing/libsignal-node.git
69 error enoent
69 error enoent
69 error enoent spawn git ENOENT
70 error enoent This is related to npm not being able to find a file.
71 verbose exit [ -2, true ]
